---
title: "week19"
author: "Leon Tran"
date: "2023-12-12"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r}
options(repos = c(CRAN = "https://cran.r-project.org"))
install.packages("datapasta")

install.packages("ggplot2")
library(ggplot2)


cdc <- data.frame(
                          Year = c(1922L,
                                   1923L,1924L,1925L,1926L,1927L,1928L,
                                   1929L,1930L,1931L,1932L,1933L,1934L,1935L,
                                   1936L,1937L,1938L,1939L,1940L,1941L,
                                   1942L,1943L,1944L,1945L,1946L,1947L,1948L,
                                   1949L,1950L,1951L,1952L,1953L,1954L,
                                   1955L,1956L,1957L,1958L,1959L,1960L,
                                   1961L,1962L,1963L,1964L,1965L,1966L,1967L,
                                   1968L,1969L,1970L,1971L,1972L,1973L,
                                   1974L,1975L,1976L,1977L,1978L,1979L,1980L,
                                   1981L,1982L,1983L,1984L,1985L,1986L,
                                   1987L,1988L,1989L,1990L,1991L,1992L,1993L,
                                   1994L,1995L,1996L,1997L,1998L,1999L,
                                   2000L,2001L,2002L,2003L,2004L,2005L,
                                   2006L,2007L,2008L,2009L,2010L,2011L,2012L,
                                   2013L,2014L,2015L,2016L,2017L,2018L,
                                   2019L,2020L,2021L),
  No..Reported.Pertussis.Cases = c(107473,
                                   164191,165418,152003,202210,181411,
                                   161799,197371,166914,172559,215343,179135,
                                   265269,180518,147237,214652,227319,103188,
                                   183866,222202,191383,191890,109873,
                                   133792,109860,156517,74715,69479,120718,
                                   68687,45030,37129,60886,62786,31732,28295,
                                   32148,40005,14809,11468,17749,17135,
                                   13005,6799,7717,9718,4810,3285,4249,
                                   3036,3287,1759,2402,1738,1010,2177,2063,
                                   1623,1730,1248,1895,2463,2276,3589,
                                   4195,2823,3450,4157,4570,2719,4083,6586,
                                   4617,5137,7796,6564,7405,7298,7867,
                                   7580,9771,11647,25827,25616,15632,10454,
                                   13278,16858,27550,18719,48277,28639,
                                   32971,20762,17972,18975,15609,18617,6124,
                                   2116)
)
ggplot(cdc) +
  aes(x = Year, y = No..Reported.Pertussis.Cases) +
  geom_point() +
  geom_line() +
  labs(title = "Reported Pertussis Cases in the United States (1922-2021)",
       x = "Year",
       y = "Number of Cases")
```

```{r}
ggplot(cdc) +
  aes(x = Year, y = No..Reported.Pertussis.Cases) +
  geom_point() +
  geom_line() +
  geom_vline(xintercept = 1946, linetype = "dashed", color = "red") +
  geom_text(aes(x = 1946, y = max(cdc$No..Reported.Pertussis.Cases), label = "wP Vaccine\nIntroduced"),
            vjust = -0.5, hjust = -0.5, color = "red") +
  geom_vline(xintercept = 1996, linetype = "dashed", color = "blue") +
  geom_text(aes(x = 1996, y = max(cdc$No..Reported.Pertussis.Cases), label = "Switch to\naP Vaccine"),
            vjust = -0.5, hjust = 1, color = "blue") +
  labs(title = "Reported Pertussis Cases in the United States (1922-2021)",
       x = "Year",
       y = "Number of Cases")
```

Q3. The introduction of the vaccine actually lowered the number of cases.

```{r}
library(jsonlite)

subject <- read_json("https://www.cmi-pb.org/api/subject", simplifyVector = TRUE)

head(subject, 3)
```
Q4.
```{r}
infancy_vac_counts <- table(subject$infancy_vac)
print(infancy_vac_counts)
```
Q5.
```{r}
sex_counts <- table(subject$biological_sex)
print(sex_counts)
```
Q6.
```{r}
race_sex_counts <- table(subject$race, subject$biological_sex)
print(race_sex_counts)
```
```{r}
library(lubridate)

today_date <- today()
cat("Today's Date:", today_date, "\n")

days_since_2000 <- today() - ymd("2000-01-01")
cat("Days Since New Year 2000:", days_since_2000, "\n")

years_since_2000 <- time_length(days_since_2000, "years")
cat("Days Since New Year 2000 in Years:", years_since_2000, "\n")
```

Q8.
```{r}
int <- ymd(subject$date_of_boost) - ymd(subject$year_of_birth)
age_at_boost <- time_length(int, "year")
head(age_at_boost)
```
Q9. They are significantly different

```{r}
install.packages("jsonlite")
library(jsonlite)

specimen <- read_json("https://www.cmi-pb.org/api/specimen", simplifyVector = TRUE)

titer <- read_json("https://www.cmi-pb.org/api/v4/plasma_ab_titer", simplifyVector = TRUE)

```

Q9.
```{r}
library(dplyr)
meta <- inner_join(specimen, subject)

dim(meta)

head(meta)

```

Q10.
```{r}
library(dplyr)
library(jsonlite)

titer <- read_json("https://www.cmi-pb.org/api/v4/plasma_ab_titer", simplifyVector = TRUE)
abdata <- inner_join(meta, titer, by = "specimen_id")

dim(abdata)

```

Q11.
```{r}
table(abdata$isotype)
```

Q12. 
```{r}
dataset_counts <- table(abdata$dataset)
sort(dataset_counts, decreasing = TRUE)
```

```{r}
igg <- abdata %>% filter(isotype == "IgG")
head(igg)
```

Q13.
```{r}
library(ggplot2)
ggplot(igg) +
  aes(x = MFI_normalised, y = antigen) +
  geom_boxplot() + 
  xlim(0, 75) +
  facet_wrap(vars(visit), nrow = 2)
```
```{r}
ggplot(igg) +
  aes(MFI_normalised, antigen, col=infancy_vac ) +
  geom_boxplot(show.legend = FALSE) + 
  facet_wrap(vars(visit), nrow=2) +
  xlim(0,75) +
  theme_bw()
```

```{r}
igg %>% filter(visit != 8) %>%
ggplot() +
  aes(MFI_normalised, antigen, col=infancy_vac ) +
  geom_boxplot(show.legend = FALSE) + 
  xlim(0,75) +
  facet_wrap(vars(infancy_vac, visit), nrow=2)
```

```{r}
filter(igg, antigen == "OVA") %>%
  ggplot() +
  aes(x = MFI_normalised, col = infancy_vac) +
  geom_boxplot(show.legend = TRUE) +
  facet_wrap(vars(visit)) +
  theme_bw()
```
```{r}
filter(igg, antigen == "PT") %>%
  ggplot() +
  aes(x = MFI_normalised, col = infancy_vac) +
  geom_boxplot(show.legend = TRUE) +
  facet_wrap(vars(visit)) +
  theme_bw()

```



```{r}
abdata.21 <- abdata %>% filter(dataset == "2021_dataset")

abdata.21 %>% 
  filter(isotype == "IgG",  antigen == "PT") %>%
  ggplot() +
    aes(x=planned_day_relative_to_boost,
        y=MFI_normalised,
        col=infancy_vac,
        group=subject_id) +
    geom_point() +
    geom_line() +
    geom_vline(xintercept=0, linetype="dashed") +
    geom_vline(xintercept=14, linetype="dashed") +
  labs(title="2021 dataset IgG PT",
       subtitle = "Dashed lines indicate day 0 (pre-boost) and 14 (apparent peak levels)")
```

